**Introduction to NumPy**

Importing NumPy module

In [8]:
import numpy as np

In [9]:
mylist = [1 ,2 ,3]

In [10]:
numpy.array(mylist)

array([1, 2, 3])

In [11]:
nparray = numpy.array(mylist)

In [12]:
nparray

array([1, 2, 3])

In [13]:
nparray = numpy.array([1, 2, 3])

In [14]:
nparray

array([1, 2, 3])

In [15]:
np.array(mylist)

array([1, 2, 3])

In [17]:
from numpy import *

In [18]:
nparray = array([1, 2, 3])

In [19]:
nparray

array([1, 2, 3])

In [1]:
import numpy as np

In [3]:
# 3 by 3, 1 - 9
matrix = [ [1, 2, 3],
           [4, 5, 6],          
           [7, 8, 9] ]      

In [4]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np_matrix = np.array(matrix)

In [6]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np_matrix = np.array([ [1, 2, 3],
                       [4, 5, 6],          
                        [7, 8, 9] ] )

In [8]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arange

In [14]:
# The above function is similar to Python's range() function

In [9]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
arr = np.arange(1, 11)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# even numbers from 0 - 10
arr = np.arange(0, 11, 2)

In [13]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [15]:
# numbers from 0 - 20, by passing only one 
# argument to arange()
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

**Generating zeros and ones**

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros(10)

In [18]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
shape = (3, 3)
np.zeros(shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((3, 3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

linspace **Dont confuse it with arange**

In [24]:
# 0 - 1, 10 equispaced values
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**eye** (For identity matrix)

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
from random import randint

In [36]:
randint(1, 5)

1

**rand**

In [37]:
np.random.rand(2) # [0, 1)

array([0.44980688, 0.8819953 ])

In [38]:
np.random.rand(2,2)

array([[0.74239457, 0.01442752],
       [0.39912672, 0.30532464]])

**randn**

In [39]:
np.random.randn(2)

array([2.98352184, 0.56840933])

In [40]:
np.random.randn(5, 5)

array([[ 0.49170821, -0.86359084, -0.97631232, -0.29088994,  0.25787358],
       [-0.68693106,  2.89778105,  0.39236018,  0.14786928, -0.07173847],
       [ 0.10736948,  1.31838359, -0.35075545,  0.90534371,  1.20588013],
       [ 0.78951155, -1.01750002, -1.42736783, -2.29611956, -1.08047006],
       [ 0.75736176,  0.25574871, -0.83781171,  0.35298554,  2.33599574]])

**randint**

In [42]:
# low (inclusive) - high (exclusive)

In [44]:
np.random.randint(1, 100)

46

In [45]:
np.random.randint(1, 100, 10)

array([62, 34, 45, 18, 46, 56, 26, 13, 36, 29])

# Array Attributes and Methods

**Reshape**

In [46]:
arr = np.linspace(0, 1, 9)

In [47]:
arr

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [48]:
arr.reshape(3, 3)

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [49]:
arr.reshape(3, 4) # 12 values

ValueError: cannot reshape array of size 9 into shape (3,4)

In [50]:
arr.reshape(2, 2)

ValueError: cannot reshape array of size 9 into shape (2,2)

In [52]:
# Create a 5 by 5 matrix having random integers between 1, 100
np.random.randint(1, 100, 25).reshape(5, 5)

array([[90, 93, 66, 29, 53],
       [ 7, 21, 60, 55, 61],
       [ 9, 33, 47, 54, 40],
       [46, 29,  1, 42, 27],
       [ 3, 89, 60,  6, 67]])

In [53]:
ranarr = np.random.randint(0, 50, 10)

**max, min, argmax, argmin**

In [54]:
ranarr

array([49,  9, 27, 49, 26, 22, 17,  3, 30,  1])

In [55]:
ranarr.max()

49

In [56]:
ranarr.min()

1

In [57]:
#Returns position of maximum argumnent
ranarr.argmax()

0

In [58]:
ranarr.argmin()

9

**shape**

In [59]:
ranarr.shape

(10,)

In [60]:
type(ranarr.shape)

tuple

In [61]:
np.random.randint(1, 100, 25).reshape(5, 5).shape

(5, 5)

In [62]:
arr = np.arange(1, 26)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [64]:
arr.reshape(1, 25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [65]:
arr.reshape(25, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

**dtype**

In [66]:
arr = np.linspace(0, 1, 10)

In [67]:
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [68]:
arr.dtype

dtype('float64')

In [69]:
np.arange(0, 10).dtype

dtype('int32')

# NumPy Indexing and Selection

In [70]:
arr = np.arange(0, 11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[3]

3

In [73]:
arr[0:4]

array([0, 1, 2, 3])

In [74]:
arr[:4]

array([0, 1, 2, 3])

In [76]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Broadcasting

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
for i in range(5):
    arr[i] = 7

In [79]:
arr

array([ 7,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10])

In [80]:
arr = np.arange(0, 11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[:5] = 7

In [84]:
arr

array([ 7,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10])

In [85]:
arr = np.arange(0, 11)

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
spliced_arr = arr[2:6] # Not a Copy, This is a view to the original array

In [92]:
spliced_arr

array([2, 3, 4, 5])

In [93]:
spliced_arr[:5]

array([2, 3, 4, 5])

In [95]:
spliced_arr[:] = 8

In [96]:
spliced_arr

array([8, 8, 8, 8])

In [98]:
arr

array([ 0,  1,  8,  8,  8,  8,  6,  7,  8,  9, 10])

In [99]:
arr = np.arange(0, 11)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
spliced_arr = arr[2:6].copy()

In [102]:
spliced_arr

array([2, 3, 4, 5])

In [103]:
spliced_arr[:] = 8

In [104]:
spliced_arr

array([8, 8, 8, 8])

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2D Array

 The general format for accessing elements in a 2D array arr_2d[row][col]

In [106]:
arr_2d = np.array([ [ 5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]])

In [107]:
arr_2d[1][1]

25

In [108]:
arr_2d[1, 1] # It is recommended to use the comma notation

25

2D Array Splicing

[ [10, 15], 
  [25, 30] ]

In [110]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [111]:
arr_2d[0, :]

array([ 5, 10, 15])

In [112]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [113]:
arr_2d[:,1]

array([10, 25, 40])

# Fancy Indexing

In [115]:
arr2d = np.zeros((10, 10))

In [116]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
arr2d.shape

(10, 10)

In [119]:
# Total number of rows
arr2d.shape[0]

10

In [120]:
# Total number of cols
arr2d.shape[1]

10

In [121]:
for i in range(arr2d.shape[0]):
    arr2d[i] = i

In [122]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [127]:
arr2d[[1, 6, 7]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [128]:
arr2d[[7, 1, 6]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

Selection

In [129]:
arr = np.arange(1, 11)

In [130]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Conditional Array Element Selection**

In [135]:
# We need to create an array having elements from arr which are > 4
new_arr = []

In [137]:
for element in arr:
    if element > 4:
        new_arr.append(element)

In [139]:
new_arr = np.array(new_arr)

In [140]:
new_arr

array([ 5,  6,  7,  8,  9, 10])

In [141]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [143]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [144]:
x = 6
arr[arr > x]

array([ 7,  8,  9, 10])

# NumPy Operations

**Arithmetic**

In [145]:
arr = np.arange(0, 10)

In [146]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [148]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [149]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [150]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [151]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [152]:
temp = arr * 5

In [153]:
temp / 5

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [154]:
arr / 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [155]:
1 / 0

ZeroDivisionError: division by zero

In [156]:
1 / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [158]:
arr = np.random.randint(1, 100 , 10)

In [159]:
arr

array([93, 28, 72, 99, 10, 18, 37, 53, 50, 25])

In [160]:
2 ** 3 

8

In [161]:
arr ** 3

array([804357,  21952, 373248, 970299,   1000,   5832,  50653, 148877,
       125000,  15625], dtype=int32)

In [162]:
arr + 100

array([193, 128, 172, 199, 110, 118, 137, 153, 150, 125])

In [163]:
arr - 100

array([ -7, -72, -28,  -1, -90, -82, -63, -47, -50, -75])

In [164]:
arr * 100

array([9300, 2800, 7200, 9900, 1000, 1800, 3700, 5300, 5000, 2500])

In [165]:
arr / 100

array([0.93, 0.28, 0.72, 0.99, 0.1 , 0.18, 0.37, 0.53, 0.5 , 0.25])

# Universal Array Functions

In [166]:
arr

array([93, 28, 72, 99, 10, 18, 37, 53, 50, 25])

In [167]:
arr ** 0.5

array([9.64365076, 5.29150262, 8.48528137, 9.94987437, 3.16227766,
       4.24264069, 6.08276253, 7.28010989, 7.07106781, 5.        ])

In [168]:
np.sqrt(arr)

array([9.64365076, 5.29150262, 8.48528137, 9.94987437, 3.16227766,
       4.24264069, 6.08276253, 7.28010989, 7.07106781, 5.        ])

In [169]:
arr = np.arange(1, 11)

In [170]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [171]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [172]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [173]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [176]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])